### ISSUE TITLE
现在这个有问题

### ISSUE THREAD

**Issue by justforissue** [telegram-zhCN/tdesktop#1]
如果你想让lang_zh_Hans.strings能被正常使用的话，需要在第337行补上分号“;”，然后删掉最后一行
否则不能正常使用

不必回复（我想以后不会再登陆了）,好在telegram的错误提示比较简单易懂，不然我也蒙不出来…………

**Comment by RexPi** [comment]
Fixed

**Comment by wfjsw** [comment]
感觉应该让他删账号神马的（雾
